# model name, i.e. dvelopment, RNN, LSTM, signature
model: LSTM_DEV
# paramterisation if development is used, SO, Sp
param: SO #SO,Sp
# dataset SpeechCommands
dataset: SpeechCommands
# cuda, cpu
device: cuda
gpu_id: "0"
seed: 0
train: True
pretrained: False
optimizer: Adam 
scheduler: exponential
gamma: 1
patience: 50
weight_decay: 0.0
lr: 0.001
n_hidden1: 56 
n_hidden2: 32 
batch_size: 128
epochs: 150 #150
mfcc: True
comment: