# model name, i.e. dvelopment, RNN, LSTM, signature
model: signature
# paramterisation if development is used, unitary, orthogonal, real_symp,signature,lstm,rnn
param: s
dataset: SpeechCommands
# cuda, cpu
device: cuda
gpu_id: "4"
seed: 0
train: True
pretrained: False
optimizer: Adam 
scheduler: exponential
gamma: 1
weight_decay: 0.0
lr: 0.001
n_hidden1: 0 
n_hidden2: 0
depth: 3
patience: 50
batch_size: 128
epochs: 150 #150
mfcc: True
comment: