# model name, i.e. dvelopment, RNN, LSTM, signature
model: LSTM
# paramterisation if development is used, unitary, orthogonal, real_symp,signature,lstm,rnn
param: a
# dataset MNIST, SpeechCommands, HFT, MNIST_seq
dataset: sMNIST
# cuda, cpu
device: cuda
gpu_id: "2"
seed: 0
train: True
pretrained: False
optimizer: Adam
scheduler: exponential
gamma: 0.997
patience: 50
weight_decay: 0.0
lr: 0.005
n_hidden1: 130 #sig-10 dev-30
n_hidden2: 0 # sig-72 dev-32
batch_size: 128
epochs: 200
permuted: True
comment: