# model name, i.e. dvelopment, RNN, LSTM, signature
model: Exprnn
# paramterisation if development is used, unitary, orthogonal, real_symp,signature,lstm,rnn
param: a
# dataset MNIST, SpeechCommands, HFT, MNIST_seq
dataset: CharTrajectories
#drop off rate
drop_rate : 0
# cuda, cpu
device: cuda
gpu_id: "2"
seed: 0
train: True
pretrained: False
optimizer: Adam 
scheduler: exponential
gamma: 0.997
weight_decay: 0.0
lr: 0.002
n_hidden1: 72
n_hidden2: 
mode: exprnn
batch_size: 32
epochs: 150
patience: 50
sr_train: 2
sr_test: 1
comment: