# model name, i.e. dvelopment, RNN, LSTM, signature
model: LSTM
# paramterisation if development is used, unitary, orthogonal, real_symp,signature,lstm,rnn
param: s
# dataset MNIST, SpeechCommands, HFT, MNIST_seq
dataset: CharTrajectories
#drop off rate
drop_rate : 0.3
# cuda, cpu
device: cuda
gpu_id: "0"
seed: 0
train: True
pretrained: False
optimizer: Adam 
scheduler: exponential
gamma: 0.997
weight_decay: 0.0
lr: 0.003
n_hidden1: 40
n_hidden2: 
batch_size: 32
epochs: 150
patience: 50
sr_train: 1
sr_test: 1
comment: