# model name, i.e. dvelopment, RNN, LSTM, signature
model: DEV
# paramterisation if development is used, SO
param: SO
# dataset MNIST, SpeechCommands, HFT, MNIST_seq
dataset: CharTrajectories
#drop off rate
drop_rate : 0.3
# cuda, cpu
device: cuda
gpu_id: "0"
seed: 0
train: True
pretrained: False
optimizer: Adam 
scheduler: exponential
gamma: 1
weight_decay: 0.0
lr: 0.001
n_hidden1: 20
n_hidden2: 20
batch_size: 32
epochs: 150
patience: 50
comment: