# model name, i.e. dvelopment, RNN, LSTM, signature
model: Exprnn
# paramterisation if development is used, unitary, orthogonal, real_symp,signature,lstm,rnn
param: a
# dataset MNIST, SpeechCommands, HFT, MNIST_seq
dataset: CIFAR10
# cuda, cpu
device: cuda
gpu_id: "0"
seed: 0
train: True
pretrained: False
optimizer: Adam 
scheduler: exponential
gamma: 0.998
patience: 50
weight_decay: 0.0
lr: 0.002
n_hidden1: 360 #sig-10 dev-30
n_hidden2: 360 # sig-72 dev-32
batch_size: 128
epochs: 200
permuted: True
length: 
mode: dtriv #dtriv or exprnn
comment: